{
  "comments": [
    {
      "key": {
        "uuid": "d2af39f8_a52c7665",
        "filename": "occ_finder.cpp",
        "patchSetId": 1
      },
      "lineNbr": 51,
      "author": {
        "id": 1000238
      },
      "writtenOn": "2021-06-10T21:01:29Z",
      "side": 0,
      "message": "If there is a method error, what will the read return?  Does caller need to know if it failed?",
      "revId": "4c1079e71ae3ecbce8a9ddc33ee4e7d623d66568",
      "serverId": "adbd0a64-1f21-4d83-b585-671fe73cb6e4",
      "unresolved": true
    },
    {
      "key": {
        "uuid": "d319a3c2_d226afa3",
        "filename": "occ_finder.cpp",
        "patchSetId": 1
      },
      "lineNbr": 51,
      "author": {
        "id": 1000397
      },
      "writtenOn": "2021-06-11T07:23:06Z",
      "side": 0,
      "message": "Yes, it will throw an exception and we should catch it when calling this method, like this:\nhttps://gerrit.openbmc-project.xyz/c/openbmc/openpower-occ-control/+/43949/1/powercap.cpp#45",
      "parentUuid": "d2af39f8_a52c7665",
      "revId": "4c1079e71ae3ecbce8a9ddc33ee4e7d623d66568",
      "serverId": "adbd0a64-1f21-4d83-b585-671fe73cb6e4",
      "unresolved": true
    }
  ]
}